apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: django_image_processor:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: sqlite-volume
          mountPath: /app/db.sqlite3
      volumes:
      - name: sqlite-volume
        hostPath:
          path: /path/to/db.sqlite3  # Replace with your database path
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
