# Generated by Django 5.1.4 on 2024-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageframe',
            name='image',
        ),
        migrations.AddField(
            model_name='imageframe',
            name='image_data',
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
